var allAlerts = 
{
	"wamalert": {
		"alerttype": "service", 
		"alertcopy": "If your People's Securities, Inc. brokerage or managed account (managed by People's United Advisors, Inc.) has not migrated to LPL Financial, please click <a href='/personal/wilmington-advisors/psi-pua' target='_blank'>here</a> to be redirected for assistance.",
		"eventdate": "",
		"startdate": "",
		"enddate": "",
		"showpagealert": false,
		"showloginealert": false,
		"showonpersonalhp": false,
		"showonbusinesshp": false,
		"forceshowonpreview": false,
		"showoncommercialhp": false,
		"shadow": true,
		"status": "",
		"icon": "notify",
		"directurls": ["/personal/wilmington-advisors"]
	},
	"2024Mortgage1098": {
		"alerttype": "scheduled", 
		"alertcopy": "1098 Statements: In mid-January, 2024, all customers will have access to their 1098 forms through Online Banking . To access your mortgage 1098, log in to <a href='https://onlinebanking.mtb.com' target='_blank'>M&T Online Banking</a>, and from the Account Summary page select 'Statements' under your M&T Mortgage account.",
		"eventdate": "",
		"startdate": "2023-12-15T01:00:00",
		"enddate": "2024-01-16T01:00:00",
		"showpagealert": true,
		"showloginealert": false,
		"showonpersonalhp": false,
		"showonbusinesshp": false,
		"forceshowonpreview": true,
		"showoncommercialhp": false,
		"shadow": true,
		"status": "",
		"icon": "notify",
		"directurls": ["/personal/mortgages-and-loans/mortgage/manage"]
	},
	"ubcalert1": {
		"alerttype": "service",
		"alertcopy": "<b>Welcome United Bank Credit Card holders</b>: Make sure to start using your new M&T credit card on May 20th, 2023, your United Bank credit card will no longer work after M﻿ay 21st, 2023. <a href='/homepage/about-us/welcome-to-mandt/peoples-united/personal-banking-faqs#united-bank'>Learn about your account transition</a>",
		"eventdate": "2023-05-19T12:00:00",
		"startdate": "2023-05-19T12:00:00",
		"enddate": "2023-05-24T12:00:00",
		"showpagealert": true,
		"showloginealert": false,
		"showonpersonalhp": true,
		"showonbusinesshp": false,
		"forceshowonpreview": false,
		"showoncommercialhp": false,
		"shadow": true,
		"status": "",
		"icon": "notify",
		"directurls": ""
	},
	"ubcalert2": {
		"alerttype": "service",
		"alertcopy": "<b>Welcome United Bank Credit Card holders</b>: Make sure to start using your new M&T credit card on May 20th, 2023, your United Bank credit card will no longer work after M﻿ay 21st, 2023. <a href='/homepage/about-us/welcome-to-mandt/peoples-united/business/business-owner-faqs#united-bank'>Learn about your account transition</a>",
		"eventdate": "2023-05-19T12:00:00",
		"startdate": "2023-05-19T12:00:00",
		"enddate": "2023-05-24T12:00:00",
		"showpagealert": true,
		"showloginealert": false,
		"showonpersonalhp": false,
		"showonbusinesshp": true,
		"forceshowonpreview": false,
		"showoncommercialhp": false,
		"shadow": true,
		"status": "",
		"icon": "notify",
		"directurls": ""
	},
	"ubcalert3": {
		"alerttype": "service",
		"alertcopy": "<b>Welcome United Bank Credit Card holders</b>: Make sure to start using your new M&T credit card on May 20th, 2023, your United Bank credit card will no longer work after M﻿ay 21st, 2023.",
		"eventdate": "2023-05-19T12:00:00",
		"startdate": "2023-05-19T12:00:00",
		"enddate": "2023-05-24T12:00:00",
		"showpagealert": true,
		"showloginealert": false,
		"showonpersonalhp": false,
		"showonbusinesshp": false,
		"forceshowonpreview": false,
		"showoncommercialhp": false,
		"shadow": true,
		"status": "",
		"icon": "notify",
		"directurls": ["/peoplesunited","/peoples-united", "/homepage/about-us/welcome-to-mandt/peoples-united/personal-banking-faqs","/homepage/about-us/welcome-to-mandt/peoples-united/business/business-owner-faqs","/homepage/about-us/welcome-to-mandt/peoples-united"]
	},
	"olboutage4323": {
		"alerttype": "service",
		"alertcopy": "M&T Online Banking is intermittently unavailable. Please consider using the mobile app while we work to resolve the issue. We apologize for the inconvenience.",
		"eventdate": "",
		"startdate": "",
		"enddate": "",
		"showpagealert": "",
		"showloginealert": false,
		"showonpersonalhp": false,
		"showonbusinesshp": false,
		"forceshowonpreview": false,
		"showoncommercialhp": false,
		"shadow": "",
		"status": "red",
		"icon": "",
		"directurls": ["/log-in"]
	},
	"axp1376": {
		"alerttype": "scheduled",
		"alertcopy": "1098 Statements: In mid-January 2023, all customers will have access to their 1098 forms through Online Banking. To access your mortgage 1098, log in to <a href='https://onlinebanking.mtb.com/'>M&T Online Banking</a>, and from the Account Summary page select 'Statements' under your M&T Mortgage account.",
		"eventdate": "2022-12-15T10:00:00",
		"startdate": "2022-12-15T10:00:00",
		"enddate": "2023-01-10T11:59:00",
		"showpagealert": true,
		"showloginealert": false,
		"showonpersonalhp": false,
		"showonbusinesshp": false,
		"forceshowonpreview": false,
		"showoncommercialhp": false,
		"shadow": true,
		"status": "",
		"icon": "notify",
		"directurls": ["/personal/mortgages-and-loans/mortgage/manage"]
	},
	"axp1377": {
		"alerttype": "scheduled",
		"alertcopy": "1098 Statements: 1098 forms are now available through Online Banking. To access your mortgage 1098, log in to <a href='https://onlinebanking.mtb.com/'>M&T Online Banking</a>, and from the Account Summary page select 'Statements' under your M&T Mortgage account.",
		"eventdate": "2023-01-18T10:00:00",
		"startdate": "2023-01-18T10:00:00",
		"enddate": "2023-04-17T11:59:00",
		"showpagealert": true,
		"showloginealert": false,
		"showonpersonalhp": false,
		"showonbusinesshp": false,
		"forceshowonpreview": false,
		"showoncommercialhp": false,
		"shadow": true,
		"status": "",
		"icon": "notify",
		"directurls": ["/personal/mortgages-and-loans/mortgage/manage"]
	},
	"christmasday": {
		"alerttype": "scheduled",
		"alertcopy": "In observance of Christmas Day, our branches will be closed on Monday, December 25, 2023. To see branch hours or make an appointment please visit our <a href='https://locations.mtb.com/' target='_blank'>branch locator page</a>.",
		"eventdate": "2023-12-25T15:00:00",
		"startdate": "2023-12-22T15:00:00",
		"enddate": "2023-12-26T07:00:00",
		"showpagealert": true,
		"showloginealert": false,
		"showonpersonalhp": true,
		"showonbusinesshp": true,
		"forceshowonpreview": false,
		"showoncommercialhp": true,
		"shadow": true,
		"status": "",
		"icon": "notify",
		"directurls": ""
	},
	"christmasdaythisyear": {
		"alerttype": "scheduled",
		"alertcopy": "In observance of Christmas, branches will be closed on Monday, December 26, 2022. To see branch hours or make an appointment please visit our <a href='https://locations.mtb.com/' target='_blank'>branch locator page</a>.",
		"eventdate": "2022-12-25T15:00:00",
		"startdate": "2022-12-23T07:00:00",
		"enddate": "2022-12-27T07:00:00",
		"showpagealert": true,
		"showloginealert": false,
		"showonpersonalhp": true,
		"showonbusinesshp": true,
		"forceshowonpreview": false,
		"showoncommercialhp": true,
		"shadow": true,
		"status": "",
		"icon": "notify",
		"directurls": ""
	},
	"independenceday": {
		"alerttype": "scheduled",
		"alertcopy": "In observance of Independence Day, our branches will be closed on Tuesday, July 4, 2023. To see branch hours or make an appointment please visit our <a href='https://locations.mtb.com/' target='_blank'>branch locator page</a>.",
		"eventdate": "2023-07-04T15:00:00",
		"startdate": "2023-07-03T15:00:00",
		"enddate": "2023-07-05T07:00:00",
		"showpagealert": true,
		"showloginealert": false,
		"showonpersonalhp": true,
		"showonbusinesshp": true,
		"forceshowonpreview": false,
		"showoncommercialhp": true,
		"shadow": true,
		"status": "",
		"icon": "notify",
		"directurls": ""
	},
	"indigenouspeoplesday": {
		"alerttype": "scheduled",
		"alertcopy": "In observance of Indigenous People's Day, our branches will be closed on Monday, October 9, 2023. To see branch hours or make an appointment please visit our <a href='https://locations.mtb.com/' target='_blank'>branch locator page</a>.",
		"eventdate": "2023-10-09T15:00:00",
		"startdate": "2023-10-06T15:00:00",
		"enddate": "2023-10-10T07:00:00",
		"showpagealert": true,
		"showloginealert": false,
		"showonpersonalhp": true,
		"showonbusinesshp": true,
		"forceshowonpreview": false,
		"showoncommercialhp": true,
		"shadow": true,
		"status": "",
		"icon": "notify",
		"directurls": ""
	},
	"juneteenth": {
		"alerttype": "scheduled",
		"alertcopy": "In observance of the Juneteenth holiday, our branches will be closed on Monday, June 19, 2023. <br />To see branch hours or make an appointment please visit our <a href='https://locations.mtb.com/' target='_blank'>branch locator page</a>.",
		"eventdate": "2023-06-19T15:00:00",
		"startdate": "2023-06-16T15:00:00",
		"enddate": "2023-06-20T07:00:00",
		"showpagealert": true,
		"showloginealert": false,
		"showonpersonalhp": true,
		"showonbusinesshp": true,
		"forceshowonpreview": false,
		"showoncommercialhp": true,
		"shadow": true,
		"status": "",
		"icon": "notify",
		"directurls": ""
	},
	"laborday": {
		"alerttype": "scheduled",
		"alertcopy": "In observance of Labor Day, our branches will be closed on Monday, September 4, 2023. To see branch hours or make an appointment please visit our <a href='https://locations.mtb.com/' target='_blank'>branch locator page</a>.",
		"eventdate": "2023-09-04T15:00:00",
		"startdate": "2023-09-01T15:00:00",
		"enddate": "2023-09-05T07:00:00",
		"showpagealert": true,
		"showloginealert": false,
		"showonpersonalhp": true,
		"showonbusinesshp": true,
		"forceshowonpreview": false,
		"showoncommercialhp": true,
		"shadow": true,
		"status": "",
		"icon": "notify",
		"directurls": ""
	},
	"martinlutherkingday": {
		"alerttype": "scheduled",
		"alertcopy": "In observance of Martin Luther King Jr. Day, our branches will be closed on Monday, January 16, 2023. To see branch hours or make an appointment please visit our <a href='https://locations.mtb.com/' target='_blank'>branch locator page</a>.",
		"eventdate": "2023-01-16T15:00:00",
		"startdate": "2023-01-13T15:00:00",
		"enddate": "2023-01-17T07:00:00",
		"showpagealert": true,
		"showloginealert": false,
		"showonpersonalhp": true,
		"showonbusinesshp": true,
		"forceshowonpreview": false,
		"showoncommercialhp": true,
		"shadow": true,
		"status": "",
		"icon": "notify",
		"directurls": ""
	},
	"memorialday": {
		"alerttype": "scheduled",
		"alertcopy": "In observance of Memorial Day, our branches will be closed on Monday, May 29, 2023. To see branch hours or make an appointment please visit our <a href='https://locations.mtb.com/' target='_blank'>branch locator page</a>.",
		"eventdate": "2023-05-29T15:00:00",
		"startdate": "2023-05-26T15:00:00",
		"enddate": "2023-05-30T07:00:00",
		"showpagealert": true,
		"showloginealert": false,
		"showonpersonalhp": true,
		"showonbusinesshp": true,
		"forceshowonpreview": false,
		"showoncommercialhp": true,
		"shadow": true,
		"status": "",
		"icon": "notify",
		"directurls": ""
	},
	"newyearsday": {
		"alerttype": "scheduled",
		"alertcopy": "In observance of New Year's Day, our branches will be closed on Monday, January 2, 2023. To see branch hours or make an appointment please visit our <a href='https://locations.mtb.com/' target='_blank'>branch locator page</a>.",
		"eventdate": "2023-01-02T15:00:00",
		"startdate": "2022-12-30T15:00:00",
		"enddate": "2023-01-03T07:00:00",
		"showpagealert": true,
		"showloginealert": false,
		"showonpersonalhp": true,
		"showonbusinesshp": true,
		"forceshowonpreview": false,
		"showoncommercialhp": true,
		"shadow": true,
		"status": "",
		"icon": "notify",
		"directurls": ""
	},
	"presidentsday": {
		"alerttype": "scheduled",
		"alertcopy": "In observance of Presidents' Day, our branches will be closed on Monday, February 20, 2023. To see branch hours or make an appointment please visit our <a href='https://locations.mtb.com/' target='_blank'>branch locator page</a>.",
		"eventdate": "2023-02-20T15:00:00",
		"startdate": "2023-02-17T15:00:00",
		"enddate": "2023-02-21T07:00:00",
		"showpagealert": true,
		"showloginealert": false,
		"showonpersonalhp": true,
		"showonbusinesshp": true,
		"forceshowonpreview": false,
		"showoncommercialhp": true,
		"shadow": true,
		"status": "",
		"icon": "notify",
		"directurls": ""
	},
	"thanksgivingday": {
		"alerttype": "scheduled",
		"alertcopy": "In observance of Thanksgiving Day, our branches will be closed on Thursday, November 23, 2023. To see branch hours or make an appointment please visit our <a href='https://locations.mtb.com/' target='_blank'>branch locator page</a>.",
		"eventdate": "2023-11-23T15:00:00",
		"startdate": "2023-11-22T15:00:00",
		"enddate": "2023-11-24T07:00:00",
		"showpagealert": true,
		"showloginealert": false,
		"showonpersonalhp": true,
		"showonbusinesshp": true,
		"forceshowonpreview": false,
		"showoncommercialhp": true,
		"shadow": true,
		"status": "",
		"icon": "notify",
		"directurls": ""
	},
	"veteransday": {
		"alerttype": "scheduled",
		"alertcopy": "In observance of Veterans Day, our branches will be closed on Saturday, November 11, 2023. To see branch hours or make an appointment please visit our <a href='https://locations.mtb.com/' target='_blank'>branch locator page</a>.",
		"eventdate": "2023-11-11T15:00:00",
		"startdate": "2023-11-10T15:00:00",
		"enddate": "2023-11-12T07:00:00",
		"showpagealert": true,
		"showloginealert": false,
		"showonpersonalhp": true,
		"showonbusinesshp": true,
		"forceshowonpreview": false,
		"showoncommercialhp": true,
		"shadow": true,
		"status": "",
		"icon": "notify",
		"directurls": ""
	},
	"fraudgeneral": {
		"alerttype": "fraudgeneral",
		"alertcopy": "Beware of Scams. There has been a recent increase in customers receiving links to bogus websites and requests to remotely access their devices which have resulted in customers becoming the victim of fraud. Know the signs fraud and what to do if you're in doubt. Learn More >",
		"eventdate": "",
		"startdate": "",
		"enddate": "",
		"showpagealert": "",
		"showloginealert": false,
		"showonpersonalhp": false,
		"showonbusinesshp": false,
		"forceshowonpreview": false,
		"showoncommercialhp": false,
		"shadow": "",
		"status": "green",
		"icon": "",
		"directurls": ""
	},
	"impactall": {
		"alerttype": "impactall",
		"alertcopy": "We are experiencing multiple system issues that impact branches, Customer Service call center, and online banking. Please try back later. We apologize for the inconvenience. Stay informed>",
		"eventdate": "",
		"startdate": "",
		"enddate": "",
		"showpagealert": "",
		"showloginealert": false,
		"showonpersonalhp": false,
		"showonbusinesshp": false,
		"forceshowonpreview": false,
		"showoncommercialhp": false,
		"shadow": "",
		"status": "green",
		"icon": "",
		"directurls": ""
	},
	"callcenterhighvol": {
		"alerttype": "callcenterhighvol",
		"alertcopy": "The Customer Service call center is temporarily unavailable due to higher than normal call volume. Please consider calling back later or using online or mobile banking.",
		"eventdate": "",
		"startdate": "",
		"enddate": "",
		"showpagealert": "",
		"showloginealert": false,
		"showonpersonalhp": false,
		"showonbusinesshp": false,
		"forceshowonpreview": false,
		"showoncommercialhp": false,
		"shadow": "",
		"status": "green",
		"icon": "",
		"directurls": ""
	},
	"callcenteronlyclosing": {
		"alerttype": "callcenteronlyclosing",
		"alertcopy": "The Customer Service call center is temporarily unavailable. Please consider calling back later. Stay Informed >",
		"eventdate": "",
		"startdate": "",
		"enddate": "",
		"showpagealert": "",
		"showloginealert": false,
		"showonpersonalhp": false,
		"showonbusinesshp": false,
		"forceshowonpreview": false,
		"showoncommercialhp": false,
		"shadow": "",
		"status": "green",
		"icon": "",
		"directurls": ""
	},
	"branchonlyclosing": {
		"alerttype": "branchonlyclosing",
		"alertcopy": "Branches in your area may be closed due to . Visit our Branch/ATM directory for specific branch hours and information, and online and mobile banking are always open. Stay informed>",
		"eventdate": "",
		"startdate": "",
		"enddate": "",
		"showpagealert": "",
		"showloginealert": false,
		"showonpersonalhp": false,
		"showonbusinesshp": false,
		"forceshowonpreview": false,
		"showoncommercialhp": false,
		"shadow": "",
		"status": "green",
		"icon": "",
		"directurls": ""
	},
	"olboutage": {
		"alerttype": "service",
		"alertcopy": "M&T Online Banking is temporarily unavailable. If you have any questions regarding your personal M&T accounts or you would like to complete a transaction, please call 1-800-724-2440. We apologize for the inconvenience.",
		"eventdate": "",
		"startdate": "",
		"enddate": "",
		"showpagealert": "",
		"showloginealert": false,
		"showonpersonalhp": false,
		"showonbusinesshp": false,
		"forceshowonpreview": false,
		"showoncommercialhp": false,
		"shadow": "",
		"status": "green",
		"icon": "",
		"directurls": ""
	},
	"ao": {
		"alerttype": "service",
		"alertcopy": "Online account opening is temporarily unavailable and we're working to resolve the issue. We apologize for the inconvenience. For assistance, please Make an Appointment.",
		"eventdate": "",
		"startdate": "",
		"enddate": "",
		"showpagealert": "",
		"showloginealert": false,
		"showonpersonalhp": false,
		"showonbusinesshp": false,
		"forceshowonpreview": false,
		"showoncommercialhp": false,
		"shadow": "",
		"status": "green",
		"icon": "",
		"directurls": ""
	},
	"billpay": {
		"alerttype": "service",
		"alertcopy": "Bill Pay is temporarily unavailable and we're working to resolve the issue. We apologize for the inconvenience.",
		"eventdate": "",
		"startdate": "",
		"enddate": "",
		"showpagealert": "",
		"showloginealert": false,
		"showonpersonalhp": false,
		"showonbusinesshp": false,
		"forceshowonpreview": false,
		"showoncommercialhp": false,
		"shadow": "",
		"status": "green",
		"icon": "",
		"directurls": ""
	},
	"alerts": {
		"alerttype": "service",
		"alertcopy": "M&T Alerts are temporarily unavailable and we're working to resolve the issue. We apologize for the inconvenience.",
		"eventdate": "",
		"startdate": "",
		"enddate": "",
		"showpagealert": "",
		"showloginealert": false,
		"showonpersonalhp": false,
		"showonbusinesshp": false,
		"forceshowonpreview": false,
		"showoncommercialhp": false,
		"shadow": "",
		"status": "green",
		"icon": "",
		"directurls": ""
	},
	"mobilebanking": {
		"alerttype": "service",
		"alertcopy": "M&T Mobile Banking is temporarily unavailable and we're working to resolve the issue. We apologize for the inconvenience.",
		"eventdate": "",
		"startdate": "",
		"enddate": "",
		"showpagealert": "",
		"showloginealert": false,
		"showonpersonalhp": false,
		"showonbusinesshp": false,
		"forceshowonpreview": false,
		"showoncommercialhp": false,
		"shadow": "",
		"status": "green",
		"icon": "",
		"directurls": ""
	},
	"moneysmart": {
		"alerttype": "service",
		"alertcopy": "M&T Money Smart is temporarily unavailable and we're working to resolve the issue. We apologize for the inconvenience.",
		"eventdate": "",
		"startdate": "",
		"enddate": "",
		"showpagealert": "",
		"showloginealert": false,
		"showonpersonalhp": false,
		"showonbusinesshp": false,
		"forceshowonpreview": false,
		"showoncommercialhp": false,
		"shadow": "",
		"status": "green",
		"icon": "",
		"directurls": ""
	},
	"olb": {
		"alerttype": "service",
		"alertcopy": "M&T Mobile and Online Banking is temporarily unavailable and we're working to resolve the issue. We apologize for the inconvenience.",
		"eventdate": "",
		"startdate": "",
		"enddate": "",
		"showpagealert": "",
		"showloginealert": false,
		"showonpersonalhp": false,
		"showonbusinesshp": false,
		"forceshowonpreview": false,
		"showoncommercialhp": false,
		"shadow": "",
		"status": "green",
		"icon": "",
		"directurls": ""
	},
	"mcd": {
		"alerttype": "service",
		"alertcopy": "Mobile Check Deposit is temporarily unavailable and we're working to resolve the issue. We apologize for the inconvenience.",
		"eventdate": "",
		"startdate": "",
		"enddate": "",
		"showpagealert": "",
		"showloginealert": false,
		"showonpersonalhp": false,
		"showonbusinesshp": false,
		"forceshowonpreview": false,
		"showoncommercialhp": false,
		"shadow": "",
		"status": "green",
		"icon": "",
		"directurls": ""
	},
	"transfers": {
		"alerttype": "service",
		"alertcopy": "Transfers and Internal Payments through M&T Online & Mobile Banking are temporarily unavailable and we're working to resolve the issue. We apologize for the inconvenience.",
		"eventdate": "",
		"startdate": "",
		"enddate": "",
		"showpagealert": "",
		"showloginealert": false,
		"showonpersonalhp": false,
		"showonbusinesshp": false,
		"forceshowonpreview": false,
		"showoncommercialhp": false,
		"shadow": "",
		"status": "green",
		"icon": "",
		"directurls": ""
	},
	"zelle": {
		"alerttype": "service",
		"alertcopy": "Zelle is temporarily unavailable and we're working to resolve the issue. We apologize for the inconvenience.",
		"eventdate": "",
		"startdate": "",
		"enddate": "",
		"showpagealert": "",
		"showloginealert": false,
		"showonpersonalhp": false,
		"showonbusinesshp": false,
		"forceshowonpreview": false,
		"showoncommercialhp": false,
		"shadow": "",
		"status": "green",
		"icon": "",
		"directurls": ""
	}
}